// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package api

import (
	"sync"
)

// Ensure, that APIMock does implement API.
// If this is not the case, regenerate this file with moq.
var _ API = &APIMock{}

// APIMock is a mock implementation of API.
//
//	func TestSomethingThatUsesAPI(t *testing.T) {
//
//		// make and configure a mocked API
//		mockedAPI := &APIMock{
//			StartFunc: func(port string) error {
//				panic("mock out the Start method")
//			},
//		}
//
//		// use mockedAPI in code that requires API
//		// and then make assertions.
//
//	}
type APIMock struct {
	// StartFunc mocks the Start method.
	StartFunc func(port string) error

	// calls tracks calls to the methods.
	calls struct {
		// Start holds details about calls to the Start method.
		Start []struct {
			// Port is the port argument value.
			Port string
		}
	}
	lockStart sync.RWMutex
}

// Start calls StartFunc.
func (mock *APIMock) Start(port string) error {
	if mock.StartFunc == nil {
		panic("APIMock.StartFunc: method is nil but API.Start was just called")
	}
	callInfo := struct {
		Port string
	}{
		Port: port,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(port)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedAPI.StartCalls())
func (mock *APIMock) StartCalls() []struct {
	Port string
} {
	var calls []struct {
		Port string
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}
